

<html lang="en">

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/light.min.css">
</head>

<body>

    <form method="post" action="postscForm">

        <h1>Add a Sea Creature</h1>
        <label>Sea Creature name</label>
        <input type="text" name="name" placeholder="Blue Whale" required value="">
        <label>Size</label>
        <input type="number" name="size" placeholder="10" required value="">
        <label>Color</label>
        <input type="text" name="color" placeholder="Blue" required value="">
        <input type="submit" value="Add">
    </form>

    <a href="/">Back</a>

</body>

</html>